{% set name = "xymol" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xymol-{{ version }}.tar.gz
  sha256: ff9ac8aa44240052f467551ce26202aa44b23d23d5ff1b6eaf90cb767d739518

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - rdkit
    - numpy
    - matplotlib-base

test:
  imports:
    - xymol
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest -vv tests

about:
  home: https://github.com/smu-tao-group/xymol
  summary: 'eXplain Your MOLecule (XYMOL): A Python package to understand and explain atom/bond contributions of small molecules in machine learning models.'
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hhaootian
    - gitconnoisseur
